/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.prostrategy.ai.commonlib;

public class Main {

    public static void main(String[] args) {
        
    }
    public boolean someLibraryMethod() {
        return true;
    }
}
